# fly.toml app configuration file for GhostliAI

app = "ghostliai"
primary_region = "jnb"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[processes]
app = "npm run start"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1